import { NextResponse } from "next/server"
import { createServerClient } from "@/lib/supabase/server"
import { createAdminClient } from "@/lib/supabase/admin"
import sgMail from "@sendgrid/mail"
import { sendWelcomeEmail } from "@/lib/email/sendWelcomeEmail"

console.log("[v0] create-advisor route - SENDGRID_API_KEY EXISTS:", !!process.env.SENDGRID_API_KEY)

if (process.env.SENDGRID_API_KEY) {
  sgMail.setApiKey(process.env.SENDGRID_API_KEY)
} else {
  console.error("[v0] ERROR: SENDGRID_API_KEY is not configured in create-advisor route")
}

function generateTemporaryPassword(): string {
  const length = 12
  const charset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
  let password = ""
  for (let i = 0; i < length; i++) {
    password += charset.charAt(Math.floor(Math.random() * charset.length))
  }
  return password
}

export async function POST(request: Request) {
  try {
    console.log("[v0] POST handler - SENDGRID_API_KEY EXISTS:", !!process.env.SENDGRID_API_KEY)

    const supabase = await createServerClient()
    const {
      data: { user },
    } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    // Check if user is CEO
    const { data: profile } = await supabase
      .from("profiles")
      .select("role, email, full_name")
      .eq("id", user.id)
      .single()

    if (profile?.role !== "ceo") {
      return NextResponse.json({ error: "Unauthorized - CEO access required" }, { status: 403 })
    }

    const { fullName, email, phone, zoomLink, autoGenerateId, status } = await request.json()

    const adminClient = createAdminClient()

    // Check for existing user
    const { data: existingUsers } = await adminClient.auth.admin.listUsers()
    const existingUser = existingUsers?.users?.find((u) => u.email === email)

    if (existingUser) {
      return NextResponse.json({ error: "A user with this email already exists" }, { status: 400 })
    }

    const temporaryPassword = generateTemporaryPassword()

    // Create advisor user
    const { data: userData, error: createError } = await adminClient.auth.admin.createUser({
      email,
      password: temporaryPassword,
      email_confirm: true,
      user_metadata: {
        full_name: fullName,
        role: "advisor",
      },
    })

    if (createError) {
      throw new Error(createError.message || "Failed to create advisor account")
    }

    const expirationDate = new Date()
    expirationDate.setFullYear(expirationDate.getFullYear() + 1)

    // Create profile (advisor_code will be auto-generated by trigger)
    const { error: profileError } = await adminClient.from("profiles").upsert(
      {
        id: userData.user.id,
        email,
        full_name: fullName,
        phone,
        zoom_link: zoomLink || null,
        role: "advisor",
        advisor_status: status,
        supervisor_id: user.id, // CEO is the supervisor
        expires_at: expirationDate.toISOString(), // Set expiration to 1 year from now
      },
      {
        onConflict: "id",
      },
    )

    if (profileError) {
      console.error("[v0] Profile error:", profileError)
    }

    try {
      console.log("[v0] Sending welcome email to:", email)
      await sendWelcomeEmail(email, fullName, "advisor")
      console.log("[v0] Welcome email sent successfully")
    } catch (welcomeError: any) {
      console.error("[v0] Welcome email failed:", {
        message: welcomeError?.message,
        code: welcomeError?.code,
        responseBody: welcomeError?.response?.body,
      })
    }

    const requestUrl = new URL(request.url)
    const websiteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://www.fna-app.com"

    let emailSentTo = "advisor"
    let emailError = null

    const fromEmail = "noreply@fna-app.com" // Verified SendGrid sender

    try {
      console.log("[v0] Sending credentials email to advisor:", email)
      console.log("[v0] SENDGRID_API_KEY available:", !!process.env.SENDGRID_API_KEY)

      const credentialsResult = await sgMail.send({
        to: email,
        from: fromEmail,
        replyTo: profile.email,
        subject: "Your Financial Advisor Account Credentials",
        html: `
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Your Advisor Account Credentials</title>
            </head>
            <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
              <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                <h1 style="color: white; margin: 0; font-size: 28px;">Your Advisor Account</h1>
              </div>
              
              <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
                <p style="font-size: 16px; margin-bottom: 20px;">Hello ${fullName},</p>
                
                <p style="font-size: 16px; margin-bottom: 20px;">
                  ${profile.full_name || "Your CEO"} has created a financial advisor account for you. Below are your login credentials:
                </p>
                
                <div style="background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #667eea; margin: 20px 0;">
                  <p style="margin: 10px 0;"><strong>Email:</strong> ${email}</p>
                  <p style="margin: 10px 0;"><strong>Temporary Password:</strong> <code style="background: #f0f0f0; padding: 4px 8px; border-radius: 4px; font-size: 14px;">${temporaryPassword}</code></p>
                  <p style="margin: 10px 0;"><strong>Login URL:</strong> <a href="${websiteUrl}" style="color: #667eea; text-decoration: none;">${websiteUrl}</a></p>
                </div>
                
                <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px; margin: 20px 0;">
                  <p style="margin: 0; color: #856404;">
                    <strong>⚠️ Important:</strong> Please log in and change this temporary password immediately for security purposes.
                  </p>
                </div>
                
                <p style="font-size: 16px; margin-top: 20px;">
                  You can now log in to your advisor dashboard to start managing your clients and providing financial guidance.
                </p>
                
                <p style="font-size: 14px; color: #666; margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd;">
                  If you have any questions or need assistance, please contact your CEO.
                </p>
              </div>
            </body>
          </html>
        `,
      })

      if (
        credentialsResult &&
        credentialsResult[0] &&
        credentialsResult[0].body &&
        (credentialsResult[0].body as any).errors
      ) {
        throw new Error(`SendGrid returned errors: ${JSON.stringify((credentialsResult[0].body as any).errors)}`)
      }

      console.log("[v0] Credentials email sent successfully to advisor")
    } catch (emailErr: any) {
      console.error("[v0] Failed to send credentials to advisor:", {
        message: emailErr?.message,
        code: emailErr?.code,
        responseBody: emailErr?.response?.body,
      })
      emailError = emailErr.message

      try {
        console.log("[v0] Attempting fallback - sending credentials to CEO:", profile.email)
        const ceoResult = await sgMail.send({
          to: profile.email,
          from: fromEmail,
          subject: `Advisor Credentials for ${fullName}`,
          html: `
            <!DOCTYPE html>
            <html>
              <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Advisor Credentials to Forward</title>
              </head>
              <body style="font-family: Arial, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: 0 auto; padding: 20px;">
                <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                  <h1 style="color: white; margin: 0; font-size: 28px;">Advisor Credentials Created</h1>
                </div>
                
                <div style="background: #f9f9f9; padding: 30px; border-radius: 0 0 10px 10px;">
                  <p style="font-size: 16px; margin-bottom: 20px;">Hello ${profile.full_name},</p>
                  
                  <div style="background: #fff3cd; border: 1px solid #ffc107; border-radius: 8px; padding: 15px; margin: 20px 0;">
                    <p style="margin: 0; color: #856404;">
                      <strong>📧 Email Delivery Notice:</strong> The credentials email could not be delivered directly to the advisor. Please forward these credentials to them manually.
                    </p>
                  </div>
                  
                  <p style="font-size: 16px; margin-bottom: 20px;">
                    An advisor account has been created for <strong>${fullName}</strong>. Below are their login credentials:
                  </p>
                  
                  <div style="background: white; padding: 20px; border-radius: 8px; border-left: 4px solid #667eea; margin: 20px 0;">
                    <p style="margin: 10px 0;"><strong>Advisor Name:</strong> ${fullName}</p>
                    <p style="margin: 10px 0;"><strong>Email:</strong> ${email}</p>
                    <p style="margin: 10px 0;"><strong>Temporary Password:</strong> <code style="background: #f0f0f0; padding: 4px 8px; border-radius: 4px; font-size: 14px;">${temporaryPassword}</code></p>
                    <p style="margin: 10px 0;"><strong>Login URL:</strong> <a href="${websiteUrl}" style="color: #667eea; text-decoration: none;">${websiteUrl}</a></p>
                  </div>
                  
                  <p style="font-size: 16px; margin-top: 20px;">
                    Please share these credentials with ${fullName} through your preferred communication method.
                  </p>
                </div>
              </body>
            </html>
          `,
        })
        emailSentTo = "ceo"
        console.log("[v0] Credentials email sent to CEO successfully")
      } catch (ceoEmailErr: any) {
        console.error("[v0] Failed to send credentials to CEO:", {
          message: ceoEmailErr?.message,
          code: ceoEmailErr?.code,
          response: ceoEmailErr?.response?.body,
        })
        emailSentTo = "none"
      }
    }

    return NextResponse.json({
      success: true,
      message: "Advisor account created successfully",
      advisor: {
        id: userData.user.id,
        email: userData.user.email,
        name: fullName,
        expiresAt: expirationDate.toISOString(),
      },
      credentials: {
        email,
        password: temporaryPassword,
      },
      emailSentTo,
      emailError,
    })
  } catch (error: any) {
    console.error("[v0] Error creating advisor:", error)
    return NextResponse.json({ error: error.message || "Failed to create advisor account" }, { status: 500 })
  }
}
